portfolio-v1/personal_portfolio/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

portfolio-v1/personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('', views.home, name='home'),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio-v1/personal_portfolio/portfolio/urls.py
from django.urls import path
from . import views


app_name = 'portfolio'

urlpatterns = [

]

portfolio-v1/personal_portfolio/blog/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio-v1/personal_portfolio/portfolio/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=256)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio-v1/personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from . import models


# Create your views here.
def all_blogs(request):
    blogs = models.Blog.objects.order_by('-date')
    context = {
        'blogs': blogs
    }
    return render(request, 'blog/all_blogs.html', context=context)


def detail(request, blog_id):
    blog = get_object_or_404(models.Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio-v1/personal_portfolio/portfolio/views.py
from django.shortcuts import render
from . import models


# Create your views here.
def home(request):
    projects = models.Project.objects.all()
    return render(request, 'portfolio/home.html', {"projects": projects})

portfolio-v1/personal_portfolio/blog/templates/blog/all_blogs.html
<!DOCTYPE html>

{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

    <div style="text-align: center; margin-bottom: 50px">
        <h1 class="display-4">Blogs</h1>
        <h3>Dhanushka has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>
    </div>

    {% for blog in blogs %}
        <a href="{% url 'blog:detail' blog_id=blog.id %}"><p class="h2">{{ blog.title }}</p></a>
        <h5 style="margin-bottom: 20px">{{ blog.date|date:'M d Y'|upper }}</h5>
        <p class="h4">{{ blog.description|striptags|truncatechars:120 }}</p>
        <hr>
    {% endfor %}

{% endblock %}

portfolio-v1/personal_portfolio/blog/templates/blog/detail.html
<!DOCTYPE html>

{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

    <div style="text-align: center; margin-bottom: 50px">
        <h1 class="display-4 text-dark font-weight-bold">{{ blog.title }}</h1>
        <h3 class="text-secondary">{{ blog.date|date:'F jS Y' }}</h3>
    </div>

    <p>{{ blog.description|safe }}</p>

{% endblock %}

portfolio-v1/personal_portfolio/portfolio/templates/portfolio/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dhanushka Gayashan</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="container" style="margin-bottom: 40px">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'portfolio/logo.png' %}" alt="logo" style="width: 130px; height: 70px;">
        </a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link h5 text-secondary" href="{% static 'portfolio/resume.pdf' %}" target="_blank">Resume <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link h5 text-secondary" href="https://github.com/dhanushka-gayashan" target="_blank">GitHub <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link h5 text-secondary" href="https://lk.linkedin.com/in/dhanushka-gayashan" target="_blank">LinkedIn <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="btn btn-secondary" href="{% url 'blog:all' %}" role="button" style="width: 80px; margin-left: 10px">Blogs</a>
                </li>
            </ul>
        </div>
    </nav>
    </div>

    <div class="container" style="margin-bottom: 50px">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</body>
</html>

portfolio-v1/personal_portfolio/portfolio/templates/portfolio/home.html
<!DOCTYPE html>

{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

    <div style="text-align: center">
        <img src="{% static 'portfolio/dhanu_vision.jpg' %}" alt="vision"
             style="border: 2px solid aqua; margin-bottom: 20px;">

        <h1 style="margin-bottom: 80px">
            Dhanushka Gayashan is a Technical Evangelist and lives in Auckland(AKL), New Zealand
        </h1>
    </div>

    <p class="h1 ml-auto">Portfolio</p>

    <hr>

    <div class="row row-cols-1 row-cols-md-3" style="margin-top: 30px">
        {% for project in projects %}
              <div class="col mb-4">
                <div class="card shadow h-100">
                  <img src="{{ project.image.url }}" class="card-img-top" alt="project image" style="height: 300px">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description|striptags|truncatechars:100 }}</p>
                        {% if project.url %}
                            <div style="text-align: center">
                                <a href="{{ project.url }}" class="btn btn-primary stretched-link">{{ project.title }}</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
              </div>
        {% endfor %}
    </div>

{% endblock %}